// File: app/(main)/pandharpur-darshan-yatra-guide/_components/details/AiRouteDetails.jsx

import { cn } from "@/lib/utils";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Card, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Car, Train, Plane, Wind, Wallet, Clock4 } from "lucide-react";

/**
 * AiRouteDetails (Client Component)
 *
 * This component displays the detailed information for routes
 * generated by the AI, including transport method and cost.
 */
function AiRouteDetails({ data }) {
  const response = typeof data.response === 'string' ? JSON.parse(data.response) : data.response;

  return (
    <div className="p-2">
      <h3 className="font-bold text-lg mb-4">Routes from {data.startLocation} to Pandharpur</h3>
      <ScrollArea className="h-[55vh]"><div className="space-y-4 pr-4">
        {response.routes.map((route, index) => (
          <Card key={index} className={cn(route.isCheapest && "border-green-500 bg-green-50/50 dark:bg-green-900/20")}>
            <CardHeader>
              <CardTitle className="flex items-center justify-between text-base">{route.routeName}{route.isCheapest && <span className="text-xs font-medium text-green-700 dark:text-green-400 bg-green-100 dark:bg-green-900/50 px-2 py-1 rounded-full">Cheapest</span>}</CardTitle>
              <CardDescription className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs">
                <span className="flex items-center gap-1.5">{route.transportMethod === 'Car' ? <Car className="w-4 h-4" /> : route.transportMethod === 'Train' ? <Train className="w-4 h-4" /> : <Plane className="w-4 h-4" />}{route.transportMethod}</span>
                <span className="flex items-center gap-1.5"><Clock4 className="w-4 h-4" />{route.duration}</span>
                <span className="flex items-center gap-1.5"><Wallet className="w-4 h-4" />{route.estimatedCost}</span>
                <span className="flex items-center gap-1.5"><Wind className="w-4 h-4" />{route.weatherAdvisory}</span>
              </CardDescription>
            </CardHeader>
          </Card>
        ))}
      </div></ScrollArea>
    </div>
  );
}

export default AiRouteDetails;