

import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import AppShell from "./app-shell";
import { checkUser } from "@/lib/checkUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pandharpur Website",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
   const user = await checkUser();
   console.log(user)
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body suppressHydrationWarning className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <AppShell>
              <main className="min-h-screen">{children}</main>
            </AppShell>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
