// File: app/(main)/guide/_components/details/AiScheduleDetails.jsx

import { format } from "date-fns";
import { ScrollArea } from "@/components/ui/scroll-area";
import { MapPin } from "lucide-react";

/**
 * AiScheduleDetails (Client Component)
 *
 * This component displays the detailed daily schedule
 * generated by the AI.
 */
function AiScheduleDetails({ data, format }) {
  const response = typeof data.response === 'string' ? JSON.parse(data.response) : data.response;
  return (
    <div className="p-2">
      <h3 className="font-bold text-lg mb-2 text-primary">{response.scheduleTitle}</h3>
      <p className="text-sm text-muted-foreground mb-4">For {format(new Date(response.scheduleDate), "PPP")}</p>
      <ScrollArea className="h-60 pr-4">
        <div className="relative border-l-2 border-orange-200 dark:border-orange-900 pl-8 space-y-6">
          {response.timeSlots.map((slot, index) => (
            <div key={index} className="relative">
              <div className="absolute -left-[43px] top-1 bg-orange-500 h-4 w-4 rounded-full border-4 border-background"></div>
              <p className="font-semibold text-sm">{slot.startTime} - {slot.endTime}</p>
              <p className="text-base">{slot.activity}</p>
              {slot.location && <p className="text-xs text-muted-foreground flex items-center gap-1.5 mt-1"><MapPin className="w-3 h-3" />{slot.location}</p>}
            </div>
          ))}
        </div>
      </ScrollArea>
    </div>
  );
}

export default AiScheduleDetails;