// File: app/(main)/guide/_components/details/AiTripDetails.jsx

import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";

/**
 * AiTripDetails (Client Component)
 *
 * This component displays the detailed day-by-day itinerary
 * generated by the AI for a trip.
 */
function AiTripDetails({ data }) {
  const response = typeof data.response === 'string' ? JSON.parse(data.response) : data.response;
  return (
    <div className="p-2">
      <h3 className="font-bold text-lg mb-2 text-primary">{data.title}</h3>
      <p className="text-sm text-muted-foreground mb-4">{data.summary}</p>
      <Separator />
      <ScrollArea className="h-96 pr-4 mt-4">
        {response.itinerary.map(day => (
          <div key={day.day} className="mb-6">
            <h4 className="font-semibold text-md sticky top-0 bg-background py-1">Day {day.day}: {day.title}</h4>
            <div className="relative border-l-2 border-orange-200 dark:border-orange-900 pl-8 space-y-4 mt-2">
              {day.activities.map((act, i) => (
                <div key={i} className="relative">
                  <div className="absolute -left-[43px] top-1 bg-orange-500 h-4 w-4 rounded-full border-4 border-background"></div>
                  <p className="font-semibold">{act.locationName}</p>
                  <p className="text-xs text-muted-foreground">{act.time}</p>
                  <p className="text-sm mt-1">{act.description}</p>
                </div>
              ))}
            </div>
          </div>
        ))}
      </ScrollArea>
    </div>
  );
}

export default AiTripDetails;